In [53]:
     # Rules
# any live cell with less than 2 live neighbours dies 
# any live cell with more than 3 live neighbours dies
# any live cell with more than 2 or 3 live neighbours lives
# any dead cell with exactly 3 live neighbours becomes live 
import numpy as np
# Starting Array
Z=np.array([[0,0,0,0,0,0,0],
           [0,1,1,0,1,1,0],
           [1,0,0,1,0,0,1],
           [0,1,0,0,0,1,0],
           [0,0,1,0,1,0,0],
           [0,0,0,1,0,0,0]])
#r=np.random.default_rng()            
#Z=np.floor(2*r.random((Z.shape)))            
#print(Z)
N=np.zeros(Z.shape,dtype=int)
def iterate_1(Z):
    # Counting neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])
    #print(N[:,:])
    # Applying rules 
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z
#print(Z)
print()
a=10
for i in range(a): iterate_1(Z)
print('tick:%d\n'%a, Z)


tick:10
 [[0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 1 0 1 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0]]


In [52]:
import numpy as np
# starting array
A=np.array([[0,0,0,0,0,0],
           [0,0,0,0,0,0],
           [0,0,0,0,0,0],
           [0,0,0,0,0,0],
           [0,0,0,0,0,0],
           [0,0,0,0,0,0]])
B=np.zeros(A.shape,dtype=int)

def iterate_1(A):
    #counting neighbours
    B=(A[ :-2, :-2]+A[ :-2,1:-1]+A[ :-2,2: ]+
       A[1:-1, :-2]             +A[1:-1,2: ]+
       A[2: , :-2]+A[2: ,1:-1]+A[2: ,2: ] )
    print(B[:,:])
    
    #applying rules
    